
server:
  port: 8081
spring:
  dubbo:
    application:
      name: admin_provider
    registry:
      address: zookeeper://47.105.105.208:2181
    scan: com.m78.controller,com.m78.controller.bill
  thymeleaf:
      suffix: .html
      request-context-attribute: request
  jackson:
      date-format: yyyy-MM-dd
      time-zone: GMT+8
